In [1]:
from data_prep import *
from numpy import NaN
from pandas import concat
from soupsieve import select
from getters import *
from understat import *
from mergers import *
from cleaners import *
from commons import *
from statistics import *
import numpy as np

In [2]:
fpl_data = pd.read_csv('fpl_players.csv')

C:\Users\user\AppData\Local\Temp\ipykernel_14504\3490912089.py:1: DtypeWarning: Columns (5,39) have mixed types. Specify dtype option on import or set low_memory=False.
  fpl_data = pd.read_csv('fpl_players.csv')

In [3]:
fpl_data

,Unnamed: 0.1,Unnamed: 0,season_x,name,position,team_x,assists,bonus,bps,clean_sheets,...,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,team,xP
0,0,0.0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,...,0,0,0,0,55,False,0,1,NaN,NaN
1,1,1.0,2016-17,Aaron Lennon,MID,NaN,0,0,6,0,...,1,0,0,0,60,True,0,1,NaN,NaN
2,2,2.0,2016-17,Aaron Ramsey,MID,NaN,0,0,5,0,...,2,0,0,0,80,True,0,1,NaN,NaN
3,3,3.0,2016-17,Abdoulaye Doucour√©,MID,NaN,0,0,0,0,...,0,0,0,0,50,False,0,1,NaN,NaN
4,4,4.0,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,...,1,0,0,0,45,True,1,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102416,4014,NaN,NaN,Nick Pope,GK,NaN,0,0,12,0,...,2,624232,644512,20280,52,True,0,8,Newcastle,5.3
102417,4015,NaN,NaN,Oliver Skipp,MID,NaN,0,0,0,0,...,0,-249,348,597,44,True,0,8,Spurs,0.5
102418,4016,NaN,NaN,Ryan Sessegnon,DEF,NaN,0,0,7,0,...,1,1833,9157,7324,45,True,0,8,Spurs,2.3
102419,4017,NaN,NaN,Ashley Young,DEF,NaN,0,0,19,1,...,5,654,1050,396,44,True,1,8,Aston Villa,1.8
102420,4018,NaN,NaN,Philip Billing,MID,NaN,0,2,30,0,...,9,1333,2105,772,53,False,0,8,Bournemouth,4.5

In [4]:
fpl_data = transform_season_column(fpl_data)

In [5]:
fpl_data

,Unnamed: 0.1,Unnamed: 0,season,name,position,team,assists,bonus,bps,clean_sheets,...,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,team,xP
0,0,0.0,2016,Aaron Cresswell,DEF,NaN,0,0,0,0,...,0,0,0,0,55,False,0,1,NaN,NaN
1,1,1.0,2016,Aaron Lennon,MID,NaN,0,0,6,0,...,1,0,0,0,60,True,0,1,NaN,NaN
2,2,2.0,2016,Aaron Ramsey,MID,NaN,0,0,5,0,...,2,0,0,0,80,True,0,1,NaN,NaN
3,3,3.0,2016,Abdoulaye Doucour√©,MID,NaN,0,0,0,0,...,0,0,0,0,50,False,0,1,NaN,NaN
4,4,4.0,2016,Adam Forshaw,MID,NaN,0,0,3,0,...,1,0,0,0,45,True,1,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102416,4014,NaN,NaN,Nick Pope,GK,NaN,0,0,12,0,...,2,624232,644512,20280,52,True,0,8,Newcastle,5.3
102417,4015,NaN,NaN,Oliver Skipp,MID,NaN,0,0,0,0,...,0,-249,348,597,44,True,0,8,Spurs,0.5
102418,4016,NaN,NaN,Ryan Sessegnon,DEF,NaN,0,0,7,0,...,1,1833,9157,7324,45,True,0,8,Spurs,2.3
102419,4017,NaN,NaN,Ashley Young,DEF,NaN,0,0,19,1,...,5,654,1050,396,44,True,1,8,Aston Villa,1.8
102420,4018,NaN,NaN,Philip Billing,MID,NaN,0,2,30,0,...,9,1333,2105,772,53,False,0,8,Bournemouth,4.5

In [6]:
# add h_team, a_team columns to fpl_player
fpl_data = add_opp_team_for_current_season(fpl_data)
fpl_data = add_away_team_column(fpl_data)
fpl_data = add_home_team_column(fpl_data)

LENGTH (0, 41)

In [7]:
fpl_data

,Unnamed: 0.1,Unnamed: 0,season,name,position,team,assists,bonus,bps,clean_sheets,...,transfers_in,transfers_out,value,was_home,yellow_cards,GW,team,xP,a_team,h_team
0,0,0.0,2016,Aaron Cresswell,DEF,NaN,0,0,0,0,...,0,0,55,False,0,1,NaN,NaN,NaN,Chelsea
1,1,1.0,2016,Aaron Lennon,MID,NaN,0,0,6,0,...,0,0,60,True,0,1,NaN,NaN,Spurs,NaN
2,2,2.0,2016,Aaron Ramsey,MID,NaN,0,0,5,0,...,0,0,80,True,0,1,NaN,NaN,Liverpool,NaN
3,3,3.0,2016,Abdoulaye Doucour√©,MID,NaN,0,0,0,0,...,0,0,50,False,0,1,NaN,NaN,NaN,Southampton
4,4,4.0,2016,Adam Forshaw,MID,NaN,0,0,3,0,...,0,0,45,True,1,1,NaN,NaN,Stoke,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102416,4014,NaN,NaN,Nick Pope,GK,NaN,0,0,12,0,...,644512,20280,52,True,0,8,Newcastle,5.3,NaN,NaN
102417,4015,NaN,NaN,Oliver Skipp,MID,NaN,0,0,0,0,...,348,597,44,True,0,8,Spurs,0.5,NaN,NaN
102418,4016,NaN,NaN,Ryan Sessegnon,DEF,NaN,0,0,7,0,...,9157,7324,45,True,0,8,Spurs,2.3,NaN,NaN
102419,4017,NaN,NaN,Ashley Young,DEF,NaN,0,0,19,1,...,1050,396,44,True,1,8,Aston Villa,1.8,NaN,NaN
102420,4018,NaN,NaN,Philip Billing,MID,NaN,0,2,30,0,...,2105,772,53,False,0,8,Bournemouth,4.5,NaN,NaN

In [10]:
index = 0
for i, row in fpl_data.iterrows():
    print(row)
    print('')
    if row['was_home'] == 1:
        fpl_data.at[index, 'h_team'] = row['team']
    else:
        fpl_data.at[index, 'a_team'] = row['team']
        
    index += 1

Unnamed: 0.1                            0
Unnamed: 0                            0.0
season                               2016
name                      Aaron Cresswell
position                              DEF
team                                  NaN
assists                                 0
bonus                                   0
bps                                     0
clean_sheets                            0
creativity                            0.0
element                               454
fixture                                10
goals_conceded                          0
goals_scored                            0
ict_index                             0.0
influence                             0.0
kickoff_time         2016-08-15T19:00:00Z
minutes                                 0
opponent_team                           4
opp_team_name                     Chelsea
own_goals                               0
penalties_missed                        0
penalties_saved                         0
red_cards                               0
round                                   1
saves                                   0
selected                            14023
team_a_score                          1.0
team_h_score                          2.0
threat                                0.0
total_points                            0
transfers_balance                       0
transfers_in                            0
transfers_out                           0
value                                  55
was_home                            False
yellow_cards                            0
GW                                      1
team                                  NaN
xP                                    NaN
a_team                                NaN
h_team                            Chelsea
Name: 0, dtype: object

ValueError: Incompatible indexer with Series

In [ ]:
fpl_data = add_missing_a_h_team(fpl_data)

In [ ]:
epl_players = get_epl_players()
fpl_data = get_fpl_data()

In [ ]:
epl_players

In [ ]:
fpl_data

In [ ]:
dataset = load_every_player(epl_players, fpl_data, rolling_columns)
excluded_columns = ['h_team_und', 'a_team_und', 'h_team_fpl', 'a_team_fpl', 'roster_id']
dataset = exclude_columns(dataset, excluded_columns)
dataset['was_home'] = dataset['was_home'].astype(int)

In [ ]:
dataset = dataset.dropna(subset = ['team'])
dataset = add_opp_team(dataset)

# team ratings
dataset = add_team_rating(dataset)
dataset = add_opposite_team_rating(dataset)
dataset = add_team_rating_diff(dataset)