# Imports

In [1]:
import os
os.chdir("D:\PulpitE\FPL_ML")

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
# loading csv
df = pd.read_csv('data/final_dataset.csv')

df = df.drop("Unnamed: 0", axis=1)

C:\users\user\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (53) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df.columns

Index(['Date', 'Day', 'Comp', 'Round', 'Venue', 'Squad', 'Opponent', 'Start',
       'Pos', 'Min',
       ...
       'MinAvgOverall', 'GlsAvgOverall', 'AstAvgOverall', 'CrdYAvgOverall',
       'CrdRAvgOverall', 'xGAvgOverall', 'xAGAvgOverall', 'CSAvgOverall',
       'Team ScoreAvgOverall', 'Opp ScoreAvgOverall'],
      dtype='object', length=117)

In [5]:
columns_to_drop = ["Comp", 
                   "Match Report", 
                   "Fls",
                   "Fld",
                   "Off",
                   "Crs",
                   "TklW",
                   "OG",
                   "PKwon",
                   "PKcon",
                   "team",
                   "index",
                   "opponent_team",
                   "red_cards",
                   "team_a_score",
                   "team_h_score",
                   "starts",
                   "ScoreForLast5",
                   "ScoreAgainstLast5",
                   "MinAvgOverall",
                   "GlsAvgOverall",
                   "AstAvgOverall",
                   "CrdYAvgOverall",
                   "CrdRAvgOverall",
                   "xGAvgOverall",
                   "CSAvgOverall",
                   'xAGAvgOverall',
                   "Team ScoreAvgOverall",
                   "Opp ScoreAvgOverall",
                   "was_home",
                   "neutral_name_y",
                   "Round",
                   "round",
                   "GoalsTeams",
                   "yellow_cards",
                   "season",
                   "opp_team_name"
                  ]

df = df.drop(columns_to_drop, axis=1)

In [6]:
df = df.drop(df[df["Squad"].isin(['Dynamo Kyiv', 'Shakhtar'])].index)

In [7]:
# df["GoalsTeams"].unique()

In [8]:
df = df.rename(columns={
    "name": "Name_original"
})

In [9]:
# df[df["CrdR"] != df["red_cards"]][["goals_scored", "Name", "Gls", "red_cards", "CrdR"]].dropna()

In [10]:
# df[[ "Round", "Fbref_GW"]]

In [11]:
# df[df["Opponent"] != df["Opp_team_name"]][["Date", "Season", "Name", "Squad", "Opponent", "Opp_team_name",]]

In [12]:
# df[df["Name"] == "Darwin-Nunez"]["goals_scored"].sum()

In [13]:
# df["starts"].isna().sum()

In [14]:
df.iloc[:,77:]

        Opp rating  Team rating  Min_points
0      1724.895874  1810.996338        True
1      1806.803955  1819.101685        True
2      1688.381104  1832.533691        True
3      1699.461792  1828.112183        True
4      1924.822632  1832.234619        True
...            ...          ...         ...
24678  2026.310791  1858.896484        True
24679  1752.288574  1816.056030       False
24680  1803.241211  1822.077881        True
24681  1796.138916  1819.507935        True
24682  1667.934448  1805.765259        True

[24573 rows x 3 columns]

In [15]:
df["value"] = (df["value"] / 10)

In [16]:
df.columns = [w[0].capitalize() + w[1:] for w in df.columns]

df = df.rename(columns={
    "GW_x": "Fbref_GW",
    "Neutral_name_x": "Clean_name",
    "Assists": "FPL_ast",
    "Position": "FPL_pos",
    "CS": "Team_CS",
    "Clean_sheets": "Player_CS",
    "Total_points": "FPL_points",
    "GW_y": "FPL_GW",
    "Expected_assists": "FPL_xA",
    "Expected_goal_involvements": "FPL_xGI",
    "Expected_goals": "FPL_xG",
    "Expected_goals_conceded": "FPL_xGC",
    "Team Score": "Team_score",
    "Goals_conceded": "Player_GC",
    "Opp Score": "Opp_score",
    "Ict_index": "ICT_index",
    "Opp rating": "Opp_rating",
    "Was Home": "Was_home",
    "XG": "xG",
    "XAG": "xA",
    "NpxG": "npxG",
    "Team rating": "Team_rating",
    "Minutes": "FPL_min",
    "Squad": "Team",
    "XP": "xP"
})

In [17]:
df = df.reset_index(drop=True)

In [18]:
# df[df["Min"] == 0][["Date", "Season", "Name", "Team", "Opponent", "FPL_opp_team",]]

In [26]:
df["Kickoff_time"]

0        2021-08-15T13:00:00Z
1        2021-08-23T19:00:00Z
2        2021-08-28T14:00:00Z
3        2021-09-11T14:00:00Z
4        2021-09-19T13:00:00Z
                 ...
24568    2023-02-05T16:30:00Z
24569    2023-05-06T14:00:00Z
24570    2023-05-13T14:00:00Z
24571    2023-05-20T11:30:00Z
24572    2023-05-28T15:30:00Z
Name: Kickoff_time, Length: 24573, dtype: object

In [19]:
# df.columns

In [20]:
df = df.reindex(columns=['Date', 'Day', 'Venue', 'Team', 'Opponent', 'Name', 'Start', 'Pos', 'Min',
       'Gls', 'Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches',
       'Tkl', 'Int', 'Blocks', 'xG', 'npxG', 'xA', 'SCA', 'GCA', 'Cmp', 'Att',
       'Cmp%', 'PrgP', 'Carries', 'PrgC', 'Att.1', 'Succ', 'Season',
       'WDL', 'Team_score', 'Opp_score', 'Team_CS', 'Was_home', 'Fbref_GW',
       'Clean_name', 'FPL_name', 'FPL_team', 'FPL_opp_team', 'Name_original',
       'FPL_pos', 'FPL_ast', 'Bonus', 'Bps', 'Player_CS', 'Creativity',
       'Element', 'Fixture', 'Player_GC', 'Goals_scored', 'ICT_index',
       'Influence', 'Kickoff_time', 'FPL_min', 'Own_goals',
       'Penalties_missed', 'Penalties_saved', 'Saves', 'Selected', 'Threat',
       'FPL_points', 'Transfers_balance', 'Transfers_in', 'Transfers_out',
       'Value', 'FPL_GW', 'xP', 'FPL_xA', 'FPL_xGI', 'FPL_xG', 'FPL_xGC',
       'Opp_rating', 'Team_rating', 'Min_points'])

In [21]:
df.tail(10)

,Date,Day,Venue,Team,Opponent,Name,Start,Pos,Min,Gls,...,Value,FPL_GW,xP,FPL_xA,FPL_xGI,FPL_xG,FPL_xGC,Opp_rating,Team_rating,Min_points
24563,2022-12-26,Mon,Away,Tottenham,Brentford,Yves-Bissouma,Y,CM,90.0,0.0,...,4.7,17.0,1.5,0.01890,0.01890,0.00,2.1526,1739.364746,1876.109375,True
24564,2023-01-01,Sun,Home,Tottenham,Aston Villa,Yves-Bissouma,Y,CM,79.0,0.0,...,4.7,18.0,1.5,0.06801,0.06801,0.00,0.7698,1739.823853,1873.475220,True
24565,2023-01-15,Sun,Home,Tottenham,Arsenal,Yves-Bissouma,N,CM,15.0,0.0,...,4.7,20.0,1.1,0.01070,0.01070,0.00,0.0911,1931.196655,1868.577759,True
24566,2023-01-19,Thu,Away,Tottenham,Manchester City,Yves-Bissouma,N,CM,16.0,0.0,...,4.7,20.0,1.1,0.00448,0.00448,0.00,0.5054,2018.819336,1858.296509,True
24567,2023-01-23,Mon,Away,Tottenham,Fulham,Yves-Bissouma,N,AM,1.0,0.0,...,4.7,21.0,1.3,0.01071,0.01071,0.00,0.0000,1722.542114,1853.427124,True
24568,2023-02-05,Sun,Home,Tottenham,Manchester City,Yves-Bissouma,N,"CM,AM",7.0,0.0,...,4.7,22.0,0.5,0.00000,0.00000,0.00,0.2700,2026.310791,1858.896484,True
24569,2023-05-06,Sat,Home,Tottenham,Crystal Palace,Yves-Bissouma,N,0,0.0,0.0,...,4.7,35.0,0.0,0.00000,0.00000,0.00,0.0000,1752.288574,1816.056030,False
24570,2023-05-13,Sat,Away,Tottenham,Aston Villa,Yves-Bissouma,N,CM,30.0,0.0,...,4.7,36.0,0.0,0.01000,0.01000,0.00,0.0800,1803.241211,1822.077881,True
24571,2023-05-20,Sat,Home,Tottenham,Brentford,Yves-Bissouma,Y,CM,90.0,0.0,...,4.7,37.0,0.5,0.04000,0.04000,0.00,1.2900,1796.138916,1819.507935,True
24572,2023-05-28,Sun,Away,Tottenham,Leeds United,Yves-Bissouma,Y,CM,76.0,0.0,...,4.7,38.0,0.8,0.03000,0.05000,0.02,1.4000,1667.934448,1805.765259,True

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24573 entries, 0 to 24572
Data columns (total 80 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               24573 non-null  object
 1   Day                24573 non-null  object
 2   Venue              24573 non-null  object
 3   Team               24573 non-null  object
 4   Opponent           24573 non-null  object
 5   Name               24573 non-null  object
 6   Start              24573 non-null  object
 7   Pos                24550 non-null  object
 8   Min                24570 non-null  float64
 9   Gls                24573 non-null  float64
 10  Ast                24573 non-null  float64
 11  PK                 24573 non-null  float64
 12  PKatt              24573 non-null  float64
 13  Sh                 24573 non-null  float64
 14  SoT                24573 non-null  float64
 15  CrdY               24573 non-null  float64
 16  CrdR               24573 non-null  float64
 17  Touches            24378 non-null  float64
 18  Tkl                24378 non-null  float64
 19  Int                24573 non-null  float64
 20  Blocks             24378 non-null  float64
 21  xG                 24378 non-null  float64
 22  npxG               24378 non-null  float64
 23  xA                 24378 non-null  float64
 24  SCA                24378 non-null  float64
 25  GCA                24378 non-null  float64
 26  Cmp                24378 non-null  float64
 27  Att                24378 non-null  float64
 28  Cmp%               24167 non-null  float64
 29  PrgP               24378 non-null  float64
 30  Carries            24378 non-null  float64
 31  PrgC               24378 non-null  float64
 32  Att.1              24378 non-null  float64
 33  Succ               24378 non-null  float64
 34  Season             24573 non-null  object
 35  WDL                24573 non-null  object
 36  Team_score         24573 non-null  int64
 37  Opp_score          24573 non-null  int64
 38  Team_CS            24573 non-null  float64
 39  Was_home           24573 non-null  float64
 40  Fbref_GW           24573 non-null  object
 41  Clean_name         24573 non-null  object
 42  FPL_name           24573 non-null  object
 43  FPL_team           24573 non-null  object
 44  FPL_opp_team       24573 non-null  object
 45  Name_original      22151 non-null  object
 46  FPL_pos            22151 non-null  object
 47  FPL_ast            22151 non-null  float64
 48  Bonus              22151 non-null  float64
 49  Bps                22151 non-null  float64
 50  Player_CS          22151 non-null  float64
 51  Creativity         22151 non-null  float64
 52  Element            22151 non-null  float64
 53  Fixture            22151 non-null  float64
 54  Player_GC          22151 non-null  float64
 55  Goals_scored       22151 non-null  float64
 56  ICT_index          22151 non-null  float64
 57  Influence          22151 non-null  float64
 58  Kickoff_time       22151 non-null  object
 59  FPL_min            22151 non-null  float64
 60  Own_goals          22151 non-null  float64
 61  Penalties_missed   22151 non-null  float64
 62  Penalties_saved    22151 non-null  float64
 63  Saves              22151 non-null  float64
 64  Selected           22151 non-null  float64
 65  Threat             22151 non-null  float64
 66  FPL_points         22151 non-null  float64
 67  Transfers_balance  22151 non-null  float64
 68  Transfers_in       22151 non-null  float64
 69  Transfers_out      22151 non-null  float64
 70  Value              22151 non-null  float64
 71  FPL_GW             22151 non-null  float64
 72  xP                 14128 non-null  float64
 73  FPL_xA             14128 non-null  float64
 74  FPL_xGI            14128 non-null  float64
 75  FPL_xG             14128 non-null  float64
 76  FPL_xGC            14128 non-null  float64
 77  Opp_rating         24047 non-null  float64
 78  Team_rating        24542 non-null  float64
 79  Min_points         24573 non-null  bool
dtypes: bool(1), float64(59), int64(2), object(18)
memory usage: 14.8+ MB

 <strong>0. Date </strong>- YYYY-MM-DD format \
 <strong>1. Day  </strong>- day of the week \
 <strong>2. Venue </strong> - home/away \
 <strong>3. Team  </strong> - team name\
 <strong>4. Opponent   </strong> - opposite team name \
 <strong>5. Name       </strong> - player name\
 <strong>6. Start         </strong> - Y:starting eleven, N:came on from bench, Y*:starting eleven - team captain
 <strong>7. Pos           </strong> - position (fbref)
 <strong>8. Min           </strong> - minutes played
 <strong>9. Gls           </strong> - goals scored by a player (fbref)
 <strong>10. Ast           </strong> - assists achieved by a player (fbref)
 <strong>11. PK            </strong> - penalty kicks made \
 <strong>12. PKatt         </strong> - penalty kicks attempted \
 <strong>13. Sh            </strong> - shots\
 <strong>14. SoT           </strong> - shots on target\
 <strong>15. CrdY          </strong> - yellow cards\
 <strong>16. CrdR          </strong> - red cards\
 <strong>17. Touches       </strong> \
 <strong>18. Tkl           </strong> - tackles \
 <strong>19. Int           </strong> - interceptions \
 <strong>20. Blocks        </strong> - blocks \
 <strong>21. xG            </strong> - expected goals (fbref) \
 <strong>22. npxG          </strong> - non-penalty expected goals (fbref) \
 <strong>23. xA            </strong> - expected assists (fbref) \
 <strong>24. SCA           </strong> - shot-creating actions\
 <strong>25. GCA           </strong> - goal-creating actions\
 <strong>26. Cmp           </strong> - passes completed\
 <strong>27. Att           </strong> - passes attempted\
 <strong>28. Cmp%          </strong> - pass completion %\
 <strong>29. PrgP          </strong> - progressive passes\
 <strong>30. Carries       </strong> - carries\
 <strong>31. PrgC          </strong> - progressive carries\
 <strong>32. Att.1         </strong> - take-ons attempted\
 <strong>33. Succ          </strong> - successful take-ons\
 <strong>34. Season        </strong> - e.g. 2022-23\
 <strong>35. WDL           </strong> - win/draw/lose\
 <strong>36. Team_score    </strong> - goals scored by team \
 <strong>37. Opp_score     </strong> - goals scored by opposite team \
 <strong>38. Team_CS       </strong> - did team keep a clean sheet\
 <strong>39. Was_home      </strong> - was the game played home\
 <strong>40. Fbref_GW      </strong> - number of gameweek (fbref) \
 <strong>41. Clean_name    </strong> - name without language-specific characters\
 <strong>42. FPL_name      </strong> - name (FPL)\
 <strong>43. FPL_team      </strong> - team (FPL)\
 <strong>44. FPL_opp_team  </strong> - opposite team (FPL) \
 <strong>45. Name_original </strong>\
 <strong>46. FPL_pos       </strong>\
 <strong>47. FPL_ast       </strong>\
 <strong>48. Bonus         </strong> - bonus points (0-3 points)
 <strong>49. Bps                </strong> - bonus points system (FPL)
 <strong>50. Player_CS          </strong> - did player keep a clean sheet\
 <strong>51. Creativity         </strong>\
 <strong>52. Element            </strong>\
 <strong>53. Fixture            </strong> - id of a fixture in given PL season\
 <strong>54. Player_GC          </strong> - goals conceded with player on a pitch\
 <strong>55. Goals_scored       </strong> - goals scored by a player (FPL)\
 <strong>56. ICT_index          </strong>\
 <strong>57. Influence          </strong>\
 <strong>58. Kickoff_time       </strong> - YYYY-MM-DD_HH:MM:SS\
 <strong>59. FPL_min            </strong> - minutes (FPL)\
 <strong>60. Own_goals          </strong>\
 <strong>61. Penalties_missed   </strong>\
 <strong>62. Penalties_saved    </strong>\
 <strong>63. Saves              </strong>\
 <strong>64. Selected           </strong>\
 <strong>65. Threat             </strong>\
 <strong>66. FPL_points         </strong> - number of FPL points scored by a player\
 <strong>67. Transfers_balance  </strong> - difference of in and out transfers
 <strong>68. Transfers_in       </strong>\
 <strong>69. Transfers_out      </strong>\
 <strong>70. Value              </strong> - FPL price
 <strong>71. FPL_GW             </strong> - gameweek number (FPL)
 <strong>72. xP                 </strong>
 <strong>73. FPL_xA             </strong> - expected assists (FPL) \
 <strong>74. FPL_xGI            </strong> - expected goal involvement (FPL) \
 <strong>75. FPL_xG             </strong> - expected goals (FPL) \
 <strong>76. FPL_xGC            </strong> - expected goals conceded (FPL) \
 <strong>77. Opp_rating         </strong> - opposite team elo rating at the time of the game (clubelo)
 <strong>78. Team_rating        </strong> - team elo rating at the time of the game (clubelo)
 <strong>79. Min_points         </strong> - ?

In [22]:
df.to_csv('data/FPL_logs.csv')