In [1]:
import os
os.chdir("D:\PulpitE\FPL_ML")

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup
from bs4 import Comment
import time
import csv

from src.match_names import *
from config import *

pd.set_option('display.max_columns', 100)

In [3]:
df = pd.read_csv('data/previous/fpl_players.csv')

In [4]:
df["team"].unique()

array(['Brighton', 'West Ham', 'Sheffield Utd', 'Everton', 'Fulham',
       'Wolves', 'Leeds', 'Leicester', 'Liverpool', 'West Brom',
       'Arsenal', 'Southampton', 'Newcastle', 'Chelsea', 'Crystal Palace',
       'Spurs', 'Man Utd', 'Man City', 'Aston Villa', 'Burnley',
       'Watford', 'Norwich', 'Brentford', 'Bournemouth', "Nott'm Forest",
       'Luton'], dtype=object)

In [16]:
result = pd.DataFrame()
for t in current_teams_fpl:
    result = result.append(df[(df["season"] == "2022-23") & (df["position"] == "GK") & (df["team"] == t) & (df["minutes"] >= 90)])
    print(t, df[(df["season"] == "2022-23") & (df["position"] == "GK") & (df["team"] == t) & (df["minutes"] >= 90)].shape)

Arsenal (38, 44)
Aston Villa (36, 44)
Bournemouth (37, 44)
Brentford (38, 44)
Brighton (38, 44)
Burnley (0, 44)
Chelsea (37, 44)
Crystal Palace (38, 44)
Everton (38, 44)
Fulham (38, 44)
Liverpool (38, 44)
Luton (0, 44)
Man City (38, 44)
Man Utd (38, 44)
Newcastle (37, 44)
Nott'm Forest (38, 44)
Sheffield Utd (0, 44)
Spurs (37, 44)
West Ham (35, 44)
Wolves (38, 44)

In [18]:
result

,Unnamed: 0,season,name,position,team,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,xP,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts
50023,50023,2022-23,Aaron Ramsdale,GK,Arsenal,0,0,25,1,0.0,15,1,0,0,1.9,19.0,2022-08-05T19:00:00Z,90,7,Crystal Palace,0,0,0,0,1,2,1128297,2.0,0.0,0.0,6,0,0,0,50,False,0,1,NaN,NaN,NaN,NaN,NaN,NaN
50599,50599,2022-23,Aaron Ramsdale,GK,Arsenal,0,0,10,0,0.0,15,11,2,0,1.2,11.6,2022-08-13T14:00:00Z,90,10,Liverpool,0,0,0,0,2,1,1369348,2.0,4.0,0.0,1,31287,93632,62345,50,True,0,2,NaN,NaN,NaN,NaN,NaN,NaN
51184,51184,2022-23,Aaron Ramsdale,GK,Arsenal,0,0,20,1,0.0,15,21,0,0,0.8,7.6,2022-08-20T16:30:00Z,90,3,Bournemouth,0,0,0,0,3,1,1366505,3.0,0.0,0.0,6,-61359,88334,149693,50,False,0,3,NaN,NaN,NaN,NaN,NaN,NaN
51780,51780,2022-23,Aaron Ramsdale,GK,Arsenal,0,0,12,0,0.0,15,31,1,0,1.9,18.8,2022-08-27T16:30:00Z,90,9,Fulham,0,0,0,0,4,2,1422476,1.0,2.0,0.0,2,-12169,88190,100359,50,True,0,4,NaN,NaN,NaN,NaN,NaN,NaN
52382,52382,2022-23,Aaron Ramsdale,GK,Arsenal,0,0,13,0,0.0,15,41,1,0,1.7,17.4,2022-08-31T18:30:00Z,90,2,Aston Villa,0,0,0,0,5,2,1407588,1.0,2.0,0.0,2,-53340,48276,101616,50,True,0,5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72709,72709,2022-23,José Malheiro de Sá,GK,Wolves,0,0,10,0,0.0,478,334,6,0,1.6,16.4,2023-04-29T14:00:00Z,90,5,Brighton,0,0,0,0,34,2,626382,0.0,6.0,0.0,-1,-10712,12090,22802,50,False,0,34,NaN,NaN,NaN,NaN,NaN,NaN
73541,73541,2022-23,José Malheiro de Sá,GK,Wolves,0,2,25,1,0.0,478,350,0,0,2.2,22.0,2023-05-06T14:00:00Z,90,2,Aston Villa,0,0,0,0,35,3,616478,0.0,1.0,0.0,9,-15261,6762,22023,50,True,0,35,NaN,NaN,NaN,NaN,NaN,NaN
74448,74448,2022-23,Daniel Bentley,GK,Wolves,0,0,25,0,0.0,717,359,2,0,5.2,52.2,2023-05-13T14:00:00Z,90,14,Man Utd,0,0,0,0,36,8,2638,0.0,2.0,0.0,3,-332,101,433,40,False,0,36,NaN,NaN,NaN,NaN,NaN,NaN
75361,75361,2022-23,Daniel Bentley,GK,Wolves,0,0,20,0,0.0,717,370,1,0,1.8,18.0,2023-05-20T14:00:00Z,90,8,Everton,0,0,0,0,37,3,4196,1.0,1.0,0.0,3,1131,1329,198,40,True,0,37,NaN,NaN,NaN,NaN,NaN,NaN
76083,76083,2022-23,José Malheiro de Sá,GK,Wolves,0,0,12,0,0.0,478,371,5,0,0.0,0.0,2023-05-28T15:30:00Z,90,1,Arsenal,0,0,0,0,38,3,583178,0.0,5.0,0.0,1,-15209,5051,20260,50,False,0,38,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
result_summary = result.groupby("team")["total_points"].mean().sort_values()

In [25]:
result_summary.to_csv("data/misc/gk_last_season.csv")

In [26]:
result_summary

team
Bournemouth       3.216216
Nott'm Forest     3.473684
Spurs             3.486486
Everton           3.500000
West Ham          3.514286
Crystal Palace    3.631579
Arsenal           3.763158
Chelsea           3.783784
Man City          3.789474
Brighton          3.868421
Fulham            3.921053
Aston Villa       3.972222
Wolves            4.052632
Man Utd           4.236842
Liverpool         4.315789
Brentford         4.368421
Newcastle         4.405405
Name: total_points, dtype: float64