# Imports

In [1]:
import os
os.chdir("D:\PulpitE\FPL_ML")

In [2]:
import pandas as pd
import numpy as np
from vaastav.getters import *

# Constants

In [3]:
NEXT_GW = 25

# fixtures in sample
FIS = 8

CURRENT_SEASON = '2022-23'

# Upcoming fixtures

In [4]:
fixtures = get_fixtures_data()

In [5]:
df_fixtures = pd.DataFrame(fixtures)

In [6]:
df_upcoming_fixtures = df_fixtures[df_fixtures["event"] >= NEXT_GW]

In [7]:
def team_id_to_name(team_id):
    teams = ['Arsenal',
     'Aston Villa',
     'Bournemouth',
     'Brentford',
     'Brighton',
     'Chelsea',
     'Crystal Palace',
     'Everton',
     'Fulham',
     'Leicester City',
     'Leeds United',
     'Liverpool',
     'Manchester City',
     'Manchester Utd',
     'Newcastle Utd',
     "Nott'ham Forest",
     'Southampton',
     'Tottenham',
     'West Ham',
     'Wolves']
    return teams[team_id - 1]

In [8]:
df_upcoming_fixtures["Squad H"] = df_upcoming_fixtures["team_h"].apply(team_id_to_name)
df_upcoming_fixtures["Squad A"] = df_upcoming_fixtures["team_a"].apply(team_id_to_name)

C:\Users\user\AppData\Local\Temp\ipykernel_4928\3776683092.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_upcoming_fixtures["Squad H"] = df_upcoming_fixtures["team_h"].apply(team_id_to_name)
C:\Users\user\AppData\Local\Temp\ipykernel_4928\3776683092.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_upcoming_fixtures["Squad A"] = df_upcoming_fixtures["team_a"].apply(team_id_to_name)

In [9]:
df_upcoming_fixtures.rename(columns={"event": "gw"}, inplace=True)

C:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [10]:
df_upcoming_fixtures

,code,gw,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id,Squad H,Squad A
232,2293053,25.0,False,False,244,2023-02-24T20:00:00Z,0,False,False,20,NaN,9,NaN,[],2,2,75154,Fulham,Wolves
233,2293052,25.0,False,False,243,2023-02-25T15:00:00Z,0,False,False,2,NaN,8,NaN,[],2,2,75153,Everton,Aston Villa
234,2293054,25.0,False,False,245,2023-02-25T15:00:00Z,0,False,False,17,NaN,11,NaN,[],2,2,75155,Leeds United,Southampton
235,2293055,25.0,False,False,246,2023-02-25T15:00:00Z,0,False,False,1,NaN,10,NaN,[],4,3,75156,Leicester City,Arsenal
236,2293059,25.0,False,False,250,2023-02-25T15:00:00Z,0,False,False,16,NaN,19,NaN,[],2,3,75160,West Ham,Nott'ham Forest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2293185,38.0,False,False,376,2023-05-28T15:30:00Z,0,False,False,3,NaN,8,NaN,[],2,2,75286,Everton,Bournemouth
376,2293186,38.0,False,False,377,2023-05-28T15:30:00Z,0,False,False,18,NaN,11,NaN,[],3,2,75287,Leeds United,Tottenham
377,2293187,38.0,False,False,378,2023-05-28T15:30:00Z,0,False,False,19,NaN,10,NaN,[],2,3,75288,Leicester City,West Ham
378,2293188,38.0,False,False,379,2023-05-28T15:30:00Z,0,False,False,9,NaN,14,NaN,[],2,4,75289,Manchester Utd,Fulham
379,2293189,38.0,False,False,380,2023-05-28T15:30:00Z,0,False,False,12,NaN,17,NaN,[],4,2,75290,Southampton,Liverpool

In [11]:
df_upcoming_fixtures = df_upcoming_fixtures[["gw", "kickoff_time", "Squad H", "Squad A"]]

In [12]:
df_upcoming_fixtures.head(15)

       gw          kickoff_time          Squad H          Squad A
232  25.0  2023-02-24T20:00:00Z           Fulham           Wolves
233  25.0  2023-02-25T15:00:00Z          Everton      Aston Villa
234  25.0  2023-02-25T15:00:00Z     Leeds United      Southampton
235  25.0  2023-02-25T15:00:00Z   Leicester City          Arsenal
236  25.0  2023-02-25T15:00:00Z         West Ham  Nott'ham Forest
237  25.0  2023-02-25T17:30:00Z      Bournemouth  Manchester City
238  25.0  2023-02-25T19:45:00Z   Crystal Palace        Liverpool
239  25.0  2023-02-26T13:30:00Z        Tottenham          Chelsea
240  25.0  2023-03-01T19:45:00Z          Arsenal          Everton
241  25.0  2023-03-01T20:00:00Z        Liverpool           Wolves
242  26.0  2023-03-04T12:30:00Z  Manchester City    Newcastle Utd
243  26.0  2023-03-04T15:00:00Z          Arsenal      Bournemouth
244  26.0  2023-03-04T15:00:00Z      Aston Villa   Crystal Palace
245  26.0  2023-03-04T15:00:00Z         Brighton         West Ham
246  26.0  2023-03-04T15:00:00Z          Chelsea     Leeds United

# Active players

In [14]:
def get_active_players():
    previous_fixtures = pd.read_csv("data/final_dataset.csv")
    name_counts = previous_fixtures.groupby('Name').size()
    filtered_names = name_counts[name_counts >= FIS].index
    result = previous_fixtures[previous_fixtures['Name'].isin(filtered_names)].groupby('Name').tail(1)
    result = result.loc[:, ~result.columns.str.contains('^Unnamed')]
    return result

In [15]:
active_players = get_active_players()

In [16]:
active_players[["Name", "Squad"]]

                     Name         Squad
18       Brenden-Aaronson  Leeds United
38              Che-Adams   Southampton
55            Tyler-Adams  Leeds United
76       Tosin-Adarabioyo        Fulham
101       Rayan-Ait-Nouri        Wolves
...                   ...           ...
7392        Jordan-Zemura   Bournemouth
7404  Oleksandr-Zinchenko       Arsenal
7422         Hakim-Ziyech       Chelsea
7438           Kurt-Zouma      West Ham
7456      Martin-Odegaard       Arsenal

[434 rows x 2 columns]

In [17]:
picked_columns = ["Name", "gw", "kickoff_time", "Squad", "Squad H", "Squad A", "Was Home"]

In [18]:
upcoming_player_fixtures_home = active_players.rename(columns={"Squad": "Squad H"}).set_index("Squad H").join(df_upcoming_fixtures.set_index("Squad H")).reset_index(level=0)
upcoming_player_fixtures_home["Squad"] = upcoming_player_fixtures_home["Squad H"]
upcoming_player_fixtures_home["Was Home"] = True
upcoming_player_fixtures_home = upcoming_player_fixtures_home[picked_columns]

In [19]:
upcoming_player_fixtures_away = active_players.rename(columns={"Squad": "Squad A"}).set_index("Squad A").join(df_upcoming_fixtures.set_index("Squad A")).reset_index(level=0)
upcoming_player_fixtures_away["Squad"] = upcoming_player_fixtures_away["Squad A"]
upcoming_player_fixtures_away["Was Home"] = False
upcoming_player_fixtures_away = upcoming_player_fixtures_away[picked_columns]

In [20]:
upcoming_player_fixtures = pd.concat([upcoming_player_fixtures_home, upcoming_player_fixtures_away]).sort_values(by=["Name", "gw"])

In [21]:
upcoming_player_fixtures["Season"] = CURRENT_SEASON

In [22]:
upcoming_player_fixtures[upcoming_player_fixtures["Name"] == "Gabriel-Dos-Santos"]

,Name,gw,kickoff_time,Squad,Squad H,Squad A,Was Home,Season
0,Gabriel-Dos-Santos,25.0,2023-03-01T19:45:00Z,Arsenal,Arsenal,Everton,True,2022-23
0,Gabriel-Dos-Santos,25.0,2023-02-25T15:00:00Z,Arsenal,Leicester City,Arsenal,False,2022-23
1,Gabriel-Dos-Santos,26.0,2023-03-04T15:00:00Z,Arsenal,Arsenal,Bournemouth,True,2022-23
1,Gabriel-Dos-Santos,27.0,2023-03-12T14:00:00Z,Arsenal,Fulham,Arsenal,False,2022-23
2,Gabriel-Dos-Santos,28.0,2023-03-19T14:00:00Z,Arsenal,Arsenal,Crystal Palace,True,2022-23
3,Gabriel-Dos-Santos,29.0,2023-04-01T14:00:00Z,Arsenal,Arsenal,Leeds United,True,2022-23
2,Gabriel-Dos-Santos,30.0,2023-04-09T15:30:00Z,Arsenal,Liverpool,Arsenal,False,2022-23
3,Gabriel-Dos-Santos,31.0,2023-04-16T13:00:00Z,Arsenal,West Ham,Arsenal,False,2022-23
4,Gabriel-Dos-Santos,32.0,2023-04-21T19:00:00Z,Arsenal,Arsenal,Southampton,True,2022-23
4,Gabriel-Dos-Santos,33.0,2023-04-26T19:00:00Z,Arsenal,Manchester City,Arsenal,False,2022-23
5,Gabriel-Dos-Santos,34.0,2023-04-29T16:30:00Z,Arsenal,Arsenal,Chelsea,True,2022-23
5,Gabriel-Dos-Santos,35.0,2023-05-06T14:00:00Z,Arsenal,Newcastle Utd,Arsenal,False,2022-23
6,Gabriel-Dos-Santos,36.0,2023-05-13T14:00:00Z,Arsenal,Arsenal,Brighton,True,2022-23
6,Gabriel-Dos-Santos,37.0,2023-05-20T14:00:00Z,Arsenal,Nott'ham Forest,Arsenal,False,2022-23
7,Gabriel-Dos-Santos,38.0,2023-05-28T15:30:00Z,Arsenal,Arsenal,Wolves,True,2022-23

In [23]:
upcoming_player_fixtures.shape

(6422, 8)

# Loading previous fixtures

In [24]:
previous_fixtures = pd.read_csv("data/final_dataset.csv")

In [25]:
previous_fixtures

,Unnamed: 0,Date,Day,Comp,Round,Venue,Squad,Opponent,Start,Pos,...,GlsAvgOverall,AstAvgOverall,CrdYAvgOverall,CrdRAvgOverall,xGAvgOverall,xAGAvgOverall,CSAvgOverall,Team ScoreAvgOverall,Opp ScoreAvgOverall,FPLAvgOverall
0,0,2022-08-06,Sat,Premier League,Matchweek 1,Home,Leeds United,Wolves,Y,RW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2022-08-13,Sat,Premier League,Matchweek 2,Away,Leeds United,Southampton,Y,"RW,AM",...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,2.000000,1.000000,2.000000
2,2,2022-08-21,Sun,Premier League,Matchweek 3,Home,Leeds United,Chelsea,Y,AM,...,0.000000,0.000000,0.500000,0.0,0.050000,0.050000,0.000000,2.000000,1.500000,2.000000
3,3,2022-08-27,Sat,Premier League,Matchweek 4,Away,Leeds United,Brighton,Y,"AM,RW",...,0.333333,0.000000,0.333333,0.0,0.366667,0.066667,0.333333,2.333333,1.000000,4.000000
4,4,2022-08-30,Tue,Premier League,Matchweek 5,Home,Leeds United,Everton,Y,"AM,RW",...,0.250000,0.000000,0.500000,0.0,0.275000,0.050000,0.250000,1.750000,1.000000,3.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7452,7452,2022-12-26,Mon,Premier League,Matchweek 17,Home,Arsenal,West Ham,Y*,RM,...,0.461538,0.153846,0.153846,0.0,0.323077,0.200000,0.461538,2.307692,0.846154,5.230769
7453,7453,2022-12-31,Sat,Premier League,Matchweek 18,Away,Arsenal,Brighton,Y*,RM,...,0.428571,0.285714,0.142857,0.0,0.328571,0.264286,0.428571,2.357143,0.857143,5.428571
7454,7454,2023-01-03,Tue,Premier League,Matchweek 19,Home,Arsenal,Newcastle Utd,Y*,RM,...,0.466667,0.333333,0.133333,0.0,0.313333,0.300000,0.400000,2.466667,0.933333,5.733333
7455,7455,2023-01-15,Sun,Premier League,Matchweek 20,Away,Arsenal,Tottenham,Y*,RM,...,0.437500,0.312500,0.187500,0.0,0.306250,0.300000,0.437500,2.312500,0.875000,5.562500
7456,7456,2023-01-22,Sun,Premier League,Matchweek 21,Home,Arsenal,Manchester Utd,Y*,RM,...,0.470588,0.294118,0.176471,0.0,0.294118,0.294118,0.470588,2.294118,0.823529,5.705882

# Assigning team elo

In [ ]:
team_ratings = pd.read_csv("data/team_ratings_history.csv")