# Imports & load

In [1]:
import os
os.chdir("D:\PulpitE\FPL_ML")

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
# loading csv
df = pd.read_csv('data/previous/final_dataset.csv')

df = df.drop("Unnamed: 0", axis=1)

In [4]:
df.columns

Index(['Unnamed: 0.1', 'Date', 'Day', 'Comp', 'Round', 'Venue', 'Squad',
       'Opponent', 'Start', 'Pos',
       ...
       'GW_y', 'xP', 'expected_assists', 'expected_goal_involvements',
       'expected_goals', 'expected_goals_conceded', 'starts', 'neutral_name_y',
       'Opp rating', 'Team rating'],
      dtype='object', length=106)

# Dropping columns

In [5]:
columns_to_drop = ["Comp", 
                   "Match Report", 
                   "Fls",
                   "Fld",
                   "Off",
                   "Crs",
                   "TklW",
                   "OG",
                   "PKwon",
                   "PKcon",
                   "team",
                   "opponent_team",
                   "red_cards",
                   "team_a_score",
                   "team_h_score",
                   "starts",
                   "was_home",
                   "neutral_name_y",
                   "Round",
                   "round",
                   "GoalsTeams",
                   "yellow_cards",
                   "season",
                   "opp_team_name"
                  ]

df = df.drop(columns_to_drop, axis=1)

In [6]:
df = df.drop(df[df["Squad"].isin(['Dynamo Kyiv', 'Shakhtar'])].index)

In [7]:
# df["GoalsTeams"].unique()

# Renaming columns

In [8]:
df = df.rename(columns={
    "name": "Name_original"
})

In [9]:
# df[df["CrdR"] != df["red_cards"]][["goals_scored", "Name", "Gls", "red_cards", "CrdR"]].dropna()

In [10]:
# df[[ "Round", "GW"]]

In [11]:
# df[df["Opponent"] != df["Opp_team_name"]][["Date", "Season", "Name", "Squad", "Opponent", "Opp_team_name",]]

In [12]:
# df[df["Name"] == "Darwin-Nunez"]["goals_scored"].sum()

In [13]:
# df["starts"].isna().sum()

In [14]:
df.iloc[:,77:]

,expected_goal_involvements,expected_goals,expected_goals_conceded,Opp rating,Team rating
0,NaN,NaN,NaN,1681.872192,1728.483398
1,NaN,NaN,NaN,1780.006958,1738.980469
2,NaN,NaN,NaN,1795.105225,1735.531982
3,NaN,NaN,NaN,1708.091675,1744.599365
4,NaN,NaN,NaN,1844.299316,1739.216797
...,...,...,...,...,...
19416,NaN,NaN,NaN,1708.234619,1736.636841
19417,NaN,NaN,NaN,1919.368774,1673.962769
19418,NaN,NaN,NaN,1815.873413,1824.330566
19419,NaN,NaN,NaN,1875.999878,1827.994751
19420,NaN,NaN,NaN,1824.330566,1815.873413

In [15]:
df["value"] = (df["value"] / 10)

In [16]:
df.columns = [w[0].capitalize() + w[1:] for w in df.columns]

df = df.rename(columns={
    "GW_x": "GW",
    "Neutral_name_x": "Clean_name",
    "Assists": "FPL_ast",
    "Position": "FPL_pos",
    "CS": "Team_CS",
    "Clean_sheets": "Player_CS",
    "Total_points": "FPL_points",
    "GW_y": "FPL_GW",
    "Expected_assists": "FPL_xA",
    "Expected_goal_involvements": "FPL_xGI",
    "Expected_goals": "FPL_xG",
    "Expected_goals_conceded": "FPL_xGC",
    "Team Score": "Team_score",
    "Goals_conceded": "Player_GC",
    "Opp Score": "Opp_score",
    "Ict_index": "ICT_index",
    "Opp rating": "Opp_rating",
    "Was Home": "Was_home",
    "XG": "xG",
    "XAG": "xA",
    "NpxG": "npxG",
    "Team rating": "Team_rating",
    "Minutes": "FPL_min",
    "Squad": "Team",
    "XP": "xP",
    "Att.1": "T_att",
    "Succ": "T_succ"
})

In [17]:
df = df.reset_index(drop=True)

In [18]:
# df[df["Min"] == 0][["Date", "Season", "Name", "Team", "Opponent", "FPL_opp_team",]]

In [19]:
df["Kickoff_time"]

0        2021-08-21T16:30:00Z
1        2021-08-28T14:00:00Z
2        2021-09-19T13:00:00Z
3        2021-09-27T19:00:00Z
4        2021-10-02T16:30:00Z
                 ...
19416                     NaN
19417                     NaN
19418                     NaN
19419                     NaN
19420                     NaN
Name: Kickoff_time, Length: 19421, dtype: object

In [20]:
# df.columns

# Reindexing

In [21]:
df = df.reindex(columns=['Date', 'Day', 'Venue', 'Team', 'Opponent', 'Name', 'Start', 'Pos', 'Min',
       'Gls', 'Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches',
       'Tkl', 'Int', 'Blocks', 'xG', 'npxG', 'xA', 'SCA', 'GCA', 'Cmp', 'Att',
       'Cmp%', 'PrgP', 'Carries', 'PrgC', 'T_att', 'T_succ', 'Season',
       'WDL', 'Team_score', 'Opp_score', 'Team_CS', 'Was_home', 'GW',
       'Clean_name', 'FPL_name', 'FPL_team', 'FPL_opp_team', 'Name_original',
       'FPL_pos', 'FPL_ast', 'Bonus', 'Bps', 'Player_CS', 'Creativity',
       'Element', 'Fixture', 'Player_GC', 'Goals_scored', 'ICT_index',
       'Influence', 'Kickoff_time', 'FPL_min', 'Own_goals',
       'Penalties_missed', 'Penalties_saved', 'Saves', 'Selected', 'Threat',
       'FPL_points', 'Transfers_balance', 'Transfers_in', 'Transfers_out',
       'Value', 'FPL_GW', 'xP', 'FPL_xA', 'FPL_xGI', 'FPL_xG', 'FPL_xGC',
       'Opp_rating', 'Team_rating', 'Min_points'])

In [22]:
df.tail(10)

,Date,Day,Venue,Team,Opponent,Name,Start,Pos,Min,Gls,...,Value,FPL_GW,xP,FPL_xA,FPL_xGI,FPL_xG,FPL_xGC,Opp_rating,Team_rating,Min_points
19411,2023-08-11,Fri,Home,Burnley,Manchester City,Vitinho,Y,LB,90.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2077.251953,1726.401611,NaN
19412,2023-08-12,Sat,Away,West Ham,Bournemouth,Vladimir-Coufal,Y,RB,90.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1660.637939,1779.449951,NaN
19413,2023-08-12,Sat,Home,Sheffield Utd,Crystal Palace,Wes-Foderingham,Y,GK,90.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1757.395630,1644.073120,NaN
19414,2023-08-12,Sat,Home,Sheffield Utd,Crystal Palace,William-Osula,Y,FW,90.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1757.395630,1644.073120,NaN
19415,2023-08-12,Sat,Home,Arsenal,Nott'ham Forest,William-Saliba,Y,CB,90.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1673.962769,1919.368774,NaN
19416,2023-08-12,Sat,Away,Fulham,Everton,Willian,Y,LW,45.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1708.234619,1736.636841,NaN
19417,2023-08-12,Sat,Away,Nott'ham Forest,Arsenal,Willy-Boly,Y,CB,90.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1919.368774,1673.962769,NaN
19418,2023-08-13,Sun,Home,Brentford,Tottenham,Yoane-Wissa,Y,FW,71.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1815.873413,1824.330566,NaN
19419,2023-08-12,Sat,Away,Aston Villa,Newcastle Utd,Youri-Tielemans,N,"CM,LW",45.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1875.999878,1827.994751,NaN
19420,2023-08-13,Sun,Away,Tottenham,Brentford,Yves-Bissouma,Y,DM,90.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1824.330566,1815.873413,NaN

In [23]:
df.columns

Index(['Date', 'Day', 'Venue', 'Team', 'Opponent', 'Name', 'Start', 'Pos',
       'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY', 'CrdR',
       'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG', 'xA', 'SCA', 'GCA',
       'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC', 'T_att', 'T_succ',
       'Season', 'WDL', 'Team_score', 'Opp_score', 'Team_CS', 'Was_home', 'GW',
       'Clean_name', 'FPL_name', 'FPL_team', 'FPL_opp_team', 'Name_original',
       'FPL_pos', 'FPL_ast', 'Bonus', 'Bps', 'Player_CS', 'Creativity',
       'Element', 'Fixture', 'Player_GC', 'Goals_scored', 'ICT_index',
       'Influence', 'Kickoff_time', 'FPL_min', 'Own_goals', 'Penalties_missed',
       'Penalties_saved', 'Saves', 'Selected', 'Threat', 'FPL_points',
       'Transfers_balance', 'Transfers_in', 'Transfers_out', 'Value', 'FPL_GW',
       'xP', 'FPL_xA', 'FPL_xGI', 'FPL_xG', 'FPL_xGC', 'Opp_rating',
       'Team_rating', 'Min_points'],
      dtype='object')

# Summary & save

 <strong>0. Date </strong>- YYYY-MM-DD format 
 <strong>1. Day  </strong>- day of the week 
 <strong>2. Venue </strong> - home/away 
 <strong>3. Team  </strong> - team name
 <strong>4. Opponent   </strong> - opposite team name 
 <strong>5. Name       </strong> - player name
 <strong>6. Start         </strong> - Y:starting eleven, N:came on from bench, Y*:starting eleven - team captain
 <strong>7. Pos           </strong> - position (fbref)
 <strong>8. Min           </strong> - minutes played
 <strong>9. Gls           </strong> - goals scored by a player (fbref)
 <strong>10. Ast           </strong> - assists achieved by a player (fbref)
 <strong>11. PK            </strong> - penalty kicks made 
 <strong>12. PKatt         </strong> - penalty kicks attempted 
 <strong>13. Sh            </strong> - shots
 <strong>14. SoT           </strong> - shots on target
 <strong>15. CrdY          </strong> - yellow cards
 <strong>16. CrdR          </strong> - red cards
 <strong>17. Touches       </strong> - touches
 <strong>18. Tkl           </strong> - tackles 
 <strong>19. Int           </strong> - interceptions 
 <strong>20. Blocks        </strong> - blocks 
 <strong>21. xG            </strong> - expected goals (fbref) 
 <strong>22. npxG          </strong> - non-penalty expected goals (fbref) 
 <strong>23. xA            </strong> - expected assists (fbref) 
 <strong>24. SCA           </strong> - shot-creating actions
 <strong>25. GCA           </strong> - goal-creating actions
 <strong>26. Cmp           </strong> - passes completed
 <strong>27. Att           </strong> - passes attempted
 <strong>28. Cmp%          </strong> - pass completion %
 <strong>29. PrgP          </strong> - progressive passes
 <strong>30. Carries       </strong> - carries
 <strong>31. PrgC          </strong> - progressive carries
 <strong>32. T_att         </strong> - take-ons attempted
 <strong>33. T_succ        </strong> - successful take-ons
 <strong>34. Season        </strong> - e.g. 2022-23
 <strong>35. WDL           </strong> - win/draw/loss
 <strong>36. Team_score    </strong> - goals scored by team 
 <strong>37. Opp_score     </strong> - goals scored by opposite team 
 <strong>38. Team_CS       </strong> - did team keep a clean sheet
 <strong>39. Was_home      </strong> - was the game played home
 <strong>40. GW            </strong> - number of gameweek (fbref) 
 <strong>41. Clean_name    </strong> - name without language-specific characters
 <strong>42. FPL_name      </strong> - name (FPL)
 <strong>43. FPL_team      </strong> - team (FPL)
 <strong>44. FPL_opp_team  </strong> - opposite team (FPL) 
 <strong>45. Name_original </strong> - name with no hyphens
 <strong>46. FPL_pos       </strong> - in-game position 
 <strong>47. FPL_ast       </strong> - FPL assists
 <strong>48. Bonus         </strong> - bonus points (0-3 points)
 <strong>49. Bps                </strong> - bonus points system (FPL)
 <strong>50. Player_CS          </strong> - did player keep a clean sheet
 <strong>51. Creativity         </strong>
 <strong>52. Element            </strong>
 <strong>53. Fixture            </strong> - id of a fixture in given PL season
 <strong>54. Player_GC          </strong> - goals conceded with player on a pitch
 <strong>55. Goals_scored       </strong> - goals scored by a player (FPL)
 <strong>56. ICT_index          </strong>
 <strong>57. Influence          </strong>
 <strong>58. Kickoff_time       </strong> - YYYY-MM-DD_HH:MM:SS
 <strong>59. FPL_min            </strong> - minutes (FPL)
 <strong>60. Own_goals          </strong>
 <strong>61. Penalties_missed   </strong>
 <strong>62. Penalties_saved    </strong>
 <strong>63. Saves              </strong>
 <strong>64. Selected           </strong>
 <strong>65. Threat             </strong>
 <strong>66. FPL_points         </strong> - number of FPL points scored by a player
 <strong>67. Transfers_balance  </strong> - difference of in and out transfers
 <strong>68. Transfers_in       </strong>
 <strong>69. Transfers_out      </strong>
 <strong>70. Value              </strong> - FPL price
 <strong>71. FPL_GW             </strong> - gameweek number (FPL)
 <strong>72. xP                 </strong>
 <strong>73. FPL_xA             </strong> - expected assists (FPL) 
 <strong>74. FPL_xGI            </strong> - expected goal involvement (FPL) 
 <strong>75. FPL_xG             </strong> - expected goals (FPL) 
 <strong>76. FPL_xGC            </strong> - expected goals conceded (FPL) 
 <strong>77. Opp_rating         </strong> - opposite team elo rating at the time of the game (clubelo)
 <strong>78. Team_rating        </strong> - team elo rating at the time of the game (clubelo)

In [24]:
df.to_csv('data/previous/FPL_logs.csv', index=False)